#ipAddr: 127.0.0.1
server:
  port: 8080
spring:
#    sentinel:
#      transport:
#        dashboard: localhost:8333
  application:
    name: wine
  datasource:
    username: root
    password: root
    url: jdbc:mysql://121.40.90.22:3306/wine?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  session:
    store-type: redis
  redis:
    host: 121.40.90.22
    password: root
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  cloud:
    alicloud:
      access-key: LTAI4FnPLQQ1sDJqMJbcn9Nq
      secret-key: uHiOLv1Mdw14WzwYir23XtdNfXcasm
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: www-fpcs-top

glmall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
#  rabbitmq:
#    host: ${ipAddr}
#    port: 5672
#    # 指定虚拟主机
#    virtual-host: /
#    username: guest
#    password: guest
#    # 开启发送端确认
#    publisher-confirms: true
#    #　开启发送端消息抵达队列确认
#    publisher-returns: true
#    # 只要抵达队列，以异步优先回调我们这个 returnconfirm
#    template:
#      mandatory: true
#    # 手动ack消息 消息不容易丢失
#    listener:
#      simple:
#        acknowledge-mode: manual
#  mvc:
#    date-format: yyyy-MM-dd HH:mm:ss
#  zipkin:
#    base-url: ${ipAddr}:9411/
#    # 关闭我们自动的服务发现功能
#    discovery-client-enabled: false
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: status
      logic-delete-value: 1
      logic-not-delete-value: 0
#myRabbitmq:
#  queue: mall-queue
#  exchange: mall-exchange
#  routeKey: mall
#  MQConfig:
#    # 订单队列
#    queues: order.release.order.queue
#    delayQueue: order.delay.queue
#    eventExchange: order-event-exchange
#    routingKey: order.release.order
#    createOrder: order.create.order
#    # 订单自动过期时间 单位:(毫秒)
#    ttl: 900000
#    # 库存解锁队列
#    ReleaseOther: stock.release.stock.queue
#    ReleaseOtherKey: order.release.other

#alipay:
#  app_id: 2016102100732649
#  # 支付宝异步回调通知 这个来感应订单是否完成
#  notify_url: http://sthwsr.natappfree.cc/payed/notify
#  return_url: http://member.glmall.com/memberOrder.html
#  timeout: 15m

image:
  targetPath: /mydata/nginx/html/static/miniImage/
  imageUrl: https://www.homiesocial.cn/static/miniImage/
wx:
  miniapp:
    appid: wx1665a2834d959989
    secret: 3ac50cbfd17e19046d352ea560c6bd14
    token:
    aes-key:
    msg-data-format: XML
    config-storage:
      type: redistemplate
      redis:
        host: 121.40.90.22
        password: root
        port: 6379
      http-client-type: httpclient
      http-proxy-host:
      http-proxy-port:
      http-proxy-password:
      http-proxy-username:

